### PR TITLE
Update whatsapi.js

### PR DESCRIPTION
**Pull request by alamcordeiro**
Picture id parameter do generate URL profile picture based on WhatsApp web.

Example:
```
wa.on('profilePictureReceived', getPicture);

function getPicture(profilePicture){
        var num = profilePicture.from.match(/^([^@]+)/)[0]
        var pictureUrl = 'https://web.whatsapp.com/pp?t=s&u=' + num  + '%40c.us&i=' + profilePicture.pictureId;
        return pictureUrl;
}

### CODE REVIEW

**Comment by matteocontrini** [comment]
Thanks for the contribution. I appreciate that!
I will merge your pull request, because of the `id` property that was missing in the response object.

But I don't get your strategy about WhatApp Web for getting the profile picture. You are already getting the image data inside the WhatsApp response, why do you need the URL to WhatsApp Web? And please note that that URL will work only if you are logged in to Web with the browser and you already requested the picture inside the interface.

**Comment by alamcordeiro** [comment]
Thanks. 
Using picture url no need of  various request to update picture profile in database in my application. Only set URL picture and it always updated.

This example URL works ?: https://web.whatsapp.com/pp?t=s&u=5519982561856%40c.us&i=1424623631

**Comment by matteocontrini** [comment]
No.

When a contact's profile picture is updated, you *should* get a node like this:
```
rx <notification from="000@s.whatsapp.net" id="365447768" offline="0" type="picture" t="1423588509" notify="[...]">
rx   <set jid="000@s.whatsapp.net" id="1423588509"></set>
rx </notification>
```
So you can know when to request the new picture. I'd suggest to store pictures on your server or, if you have limited storage, on an image hosting provider (e.g. imgur).

The notification node posted above is not handled in the current implementation, yet.

**Comment by alamcordeiro** [comment]
Perfect, did not know the WhatsApp notify when contact modified the profile picture.

**Pull request merged**
