### PR TITLE
Registration implemented

### PR DESCRIPTION
**Pull request by Santinell**
I test only codeRequest, because don't have other sim for register.
Test code:

```javascript

var whatsapi = require('whatsapi');
var crypto = require('crypto');

var config = {
  msisdn: "1212121",
  username: "Jonny",
  device_id: crypto.randomBytes(20).toString('hex')
};

var wa = whatsapi.createAdapter(config);

wa.connect(function connected(err) {
  if (err) throw err;
  console.log('Connected');
  wa.codeRequest('sms');
});

//And after that:
//wa.codeRegister(code);

```

### CODE REVIEW

**Comment by matteocontrini** [comment]
Some things:
* the registration should be done on a separate object. The WhatsApi instance expects that you have valid data. You should move everything to the file `whatsapiregistration.js` file (and considering that there's a countries file too, you could create e `registration` folder). Then provide the new WhatsApiRegistration externally with the `createRegistration` function on the module.
* results and errors are provided with callbacks, not with events. When the response is successful, `callback(null, objectOfResponse)`. When there's an error `callback(errorObject)`. The response should be a single object and not 15 parameters or something like that. And the error object should have two properties for consistency with the rest of the module, as explained [here](https://github.com/hidespb/node-whatsapi/wiki/Error-handling). Invent the error codes if you don't have them.

**Comment by Santinell** [comment]
so if events no need, i can remove EventEmitter from parents of whatsapiregistration?

**Comment by matteocontrini** [comment]
Yes

--
Matteo
Inviato da Windows Phone

----- Messaggio originale -----
Da: "Pavel Evdokimov" <notifications@github.com>
Inviato: ‎15/‎05/‎2015 10:58
A: "hidespb/node-whatsapi" <node-whatsapi@noreply.github.com>
Cc: "Matteo Contrini" <m.contrini@gmail.com>
Oggetto: Re: [node-whatsapi] Registration implemented (#52)

so if events no need, i can remove EventEmitter from parents of whatsapiregistration?

**Comment by Santinell** [comment]
What do you think if callback will always return json response? (on success and on error - for more details e.g.)
For example:
this.request('code', params, function(response, body) {
  if (response.status === 'sent') {
    return callback(null, body);
  }

  if (response.reason === 'too_recent') {
    return callback(TOO_RECENT_ERROR, body);
  }

  callback(REQUEST_ERROR, body);
});

**Comment by matteocontrini** [comment]
You can but not as a second parameter, because the second parameter is for the successful response. Create an object for the first parameter, something like this (because I don't know what `TOO_RECENT_ERROR` is in your case:

`{ reason: 'your_reason', response: body }`

**Comment by Santinell** [comment]
Or maybe set callback on request for user cases:
this.request('code', params, callback);

**Comment by Santinell** [comment]
Fixed. How it looks now?

**Comment by Santinell** [comment]
Tested codeRegister - works too

**Comment by matteocontrini** [comment]
Thanks for testing.
Can you remove the example file and create a new page in the wiki called "Registration"?
I'll merge after that.

**Comment by Santinell** [comment]
Only create, or with text?

**Comment by matteocontrini** [comment]
Move the content of the example file in a new wiki page with the registration example/explaination :)

**Comment by matteocontrini** [comment]
[Done](https://github.com/hidespb/node-whatsapi/wiki/Number-registration). Thanks for the work!

**Comment by tvandergeer** [comment]
Great work! Thanks!

**Pull request merged**
