### PR TITLE
fixed image resizing, group changes

### PR DESCRIPTION
**Pull request by aynik**
This fixes issues when setting the profile picture (wrong size was used for thumbnail), group changes by using the correct node name (participants) and group events normalization.

### CODE REVIEW

**Comment by matteocontrini** [comment]
Hi,
* are you sure about the thumbnail size? I noticed just now that it doesn't work either with 200x200 or 96x96
* I don't get why you changed the message ID format for participants change.. is that needed? :)
* we decided to use `camelCase` for event names. I cannot accept that format

**Comment by aynik** [comment]
> are you sure about the thumbnail size? I noticed just now that it doesn't work either with 200x200 or 96x96

Yes, please check [this line in WhatsAPI's repo](https://github.com/venomous0x/WhatsAPI/blob/master/src/whatsprot.class.php#L2943), of course you should use JPG and never exceed 65355 bytes in the message (main + thumbnail).

> I don't get why you changed the message ID format for participants change.. is that needed? :)

Yes, that's needed to perform group changes, I think somebody just (badly) extrapolated [this](https://github.com/venomous0x/WhatsAPI/blob/master/src/whatsprot.class.php#L708) when it should be [like this](https://github.com/venomous0x/WhatsAPI/blob/master/src/whatsprot.class.php#L2784).

> we decided to use camelCase for event names. I cannot accept that format

Yes, you're right on that one, I was just following what I saw earlier in master, gonna fix that.

**Comment by matteocontrini** [comment]
1) I've seen that line. I changed that value to 200x200 just some days ago because there was no problem with image messages. But you're right, 96x96 is probably the right thumbnail size (that should be checked with the official app source code...).
2) you're looking at a really old WhatsAPI version. [This](https://github.com/mgp25/WhatsAPI-Official/blob/master/src/whatsprot.class.php#L1442) is the updated one. Anyway I don't think message IDs influence the process in any way...

**Comment by aynik** [comment]
> 2) you're looking at a really old WhatsAPI version. This is the updated one. Anyway I don't think message IDs influence the process in any way...

Correct, excuse my naivety, in fact I'm very new to whatsapi but I was really in a hurry to hack something with this library and I had so much fun fighting with yowsup and whatsapi that I didn't check there is a more updated fork. :)

Hope the image fix is still useful, I'm going to remove 2 and 3 from this pull request.

**Comment by matteocontrini** [comment]
Thanks for the contribution, your help is appreciated :smile:

**Pull request merged**
